
[package]
description = "Multithreading primitives."
edition = "2024"
license = "MIT OR Apache-2.0"
name = "hreads"
repository = "https://github.com/vladasz/hreads"
version = "0.13.0"

[lib]
crate-type = ["dylib", "rlib", "staticlib"]
name = "hreads"

[dependencies]
anyhow = "1.0"
log = "0.4"
parking_lot = "0.12"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
async-std = "1.13"
futures = "0.3"
pollster = "0.4"
tokio = { version = "1.49.0", features = ["full"] }

[target.'cfg(target_arch = "wasm32")'.dependencies]
gloo-timers = { version = "0.3", features = ["futures"] }
wasm-bindgen-futures = "0.4"
web-sys = { version = "0.3", features = ["Performance", "Window"] }

[dev-dependencies]
pretty_assertions = "1.4"
serial_test = "3.3"
wasm-bindgen-test = "0.3"

[target.'cfg(not(target_arch = "wasm32"))'.dev-dependencies]
fake = "4.4"

[build-dependencies]
plat = "0.8"
